### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jaimeiniesta** [PJUllrich/lemon_ex#9]
Is there any way to pass `page[size]` and `page[number]` in the API calls?

By default page size is 10 but it can be increased to 100:

https://docs.lemonsqueezy.com/api#pagination

**Comment by PJUllrich** [comment]
Hey @jaimeiniesta, I just released version `0.2.0` which allows a `page: [size: 2, number: 5]` and `sort: "-createdAt"` option when you `list`-records. I decided to make this a breaking change though and to move all current filters to a `filter: [email: "test@test.com"]` parameter to that it's explicit which options are for filtering and which are for pagination and sorting. I hope this doesn't cause you too much trouble. Otherwise, let me know and let's find a solution that works for everybody.

**Comment by jaimeiniesta** [comment]
Awesome, just in time 🚀 

I'll check it out, I don't see any trouble on the breaking changes.

Thanks!
